name: rdb_gro_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.6
  table_calendar: ^3.1.1
  intl: ^0.19.0
  
  http: ^1.1.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.4
  loading_indicator: ^3.1.1
  shimmer: ^3.0.0
  collection: ^1.17.2
  grouped_list: ^5.1.2
  local_auth: ^2.2.0
  google_maps_flutter: ^2.7.0
  geocoding: ^3.0.0
  carousel_slider_plus: ^6.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
